artifact_location: /Users/altairagamata/LifeDNA/mlops-control-tower/backend/your-mlflow-tracking-uri/0
creation_time: 1750821021123
experiment_id: '0'
last_update_time: 1750821021123
lifecycle_stage: active
name: Default
