version: '3.11'

services:
  catch-proxy:
    build: .
    container_name: mlops-ct-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
